export const VPN_CONNECTED = 'VPN_CONNECTED';
export const VPN_DISCONNECTED = 'VPN_DISCONNECTED';
export const VPN_UNKNOWN = 'VPN_UNKNOWN';
export const COUNTRY_SELECTED = 'COUNTRY_SELECTED';
export const COUNTRY_LIST = 'COUNTRY_LIST';
